### ISSUE TITLE
Bug: Doesn't play.

### ISSUE THREAD

**Issue by CitrusWire** [GDQuest/godot-2d-tactical-space-combat#5]
**I'm submitting a...**
- [ ] Bug report.

## Bug report ##
I downloaded the current version of this project (Download Code), imported the project.godot, and I get this error:

```
 res://TacticalSpaceCombat/Ship/Fire.gd:31 - Parse Error: The method "append_array" isn't declared on base "Array".
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
```

It doesn't execute either.

**Comment by NathanLovato** [comment]
That's not a bug: you need Godot 3.2.4 to play this project. I'll add it to the readme.

**Comment by NathanLovato** [comment]
Addressed with ae0f109522c698026f0248c58138f9abb99e2938

**Comment by blakelead** [comment]
For what it's worth I also encountered this issue upon my first run of this project.
I'm using Godot 3.2.3 and was able to run the project simply by setting explicitly the `out` array type:

```gdscript
func _get_neightbor_positions(at: Vector2) -> PoolVector2Array:
	var out : PoolVector2Array = []
	var point1 := tilemap.world_to_map(at)
	for offset in Utils.DIRECTIONS:
		var point2: Vector2 = point1 + offset
		if point2.x < 0 or point2.y < 0:
			continue
		
		var curve: Curve2D = tilemap.find_path(point1, point2)
		if curve.get_point_count() == 1:
			out.append_array(curve.get_baked_points())
	return out
```

In the file `res://TacticalSpaceCombat/Ship/Ship.gd` at line 221.

**Comment by NathanLovato** [comment]
Sure, the method exists on pool arrays. But we're sticking to plain arrays for this project and using Godot 3.2.4
